version: '3.8'

services:
  web:
    build: .
    container_name: menu_digital_app
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
