version: '3.8'

services:
  web:
    build: .
    container_name: menu_digital_app
    ports:
      - "80:3000"
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - PORT=3000
